# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20180306_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.AddField(
            model_name='user',
            name='friendeds',
            field=models.ManyToManyField(blank=True, related_name='_user_friendeds_+', to='login.User'),
        ),
    ]
