# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20180306_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friendeds',
            field=models.ManyToManyField(blank=True, related_name='friendsof', to='login.User'),
        ),
    ]
