# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20180306_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friendeds',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_user_friends_+', to='login.User'),
        ),
    ]
