# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20180306_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bday',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
